name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'Infrastructure/terraform/lambda.zip'
      - '.github/workflows/deploy-lambda.yml'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Verify Lambda function
        run: |
          aws lambda get-function \
            --function-name cloud-health-monitor

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name cloud-health-monitor \
            --zip-file fileb://Infrastructure/terraform/lambda.zip

      - name: Verify deployment
        run: |
          aws lambda get-function \
            --function-name cloud-health-monitor \
            --query 'Configuration.[FunctionName,Runtime,LastModified,State]' \
            --output table